version: '3.17'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE

  todolist:
    container_name: todolists
    image: todolists:latest
    ports:
      - "3030:3030"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DBNAME=$MYSQL_DATABASE
